const FilterActionTypes = {
  SET_PRICE: "SET_PRICE",
  SET_OBTAININGTYPE: "SET_OBTAININGTYPE",
  SET_REALESTATETYPE: "SET_REALESTATETYPE",
  SET_SPACE: "SET_SPACE",
  SET_ROOMS: "SET_ROOMS",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
  SET_MINIMUM_INPUT: "SET_MINIMUM_INPUT",
  SET_MAXIMAL_INPUT: "SET_MAXIMAL_INPUT",
  SET_PAGE: "SET_PAGE",
  RESET_PAGE: "RESET_PAGE",
  SET_TOTAL_PAGES: "SET_TOTAL_PAGES",
  TOGGLE_SEARCHBUTTON: "TOGGLE_SEARCHBUTTON"
};

export default FilterActionTypes;
