const FilterActionTypes = {
  SET_PREIS: "SET_PREIS",
  SET_BEZUGSART: "SET_BEZUGSART",
  SET_HAUSTYP: "SET_HAUSTYP",
  SET_FLÄCHE: "SET_FLÄCHE",
  SET_ZIMMERANZAHL: "SET_ZIMMERANZAHL",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
  SET_MINIMUM_INPUT: "SET_MINIMUM_INPUT",
  SET_MAXIMAL_INPUT: "SET_MAXIMAL_INPUT",
  SET_SEITE: "SET_SEITE"
};

export default FilterActionTypes;
