const DropdownActionTypes = {
  TOGGLE_PREISDROPDOWN_HIDDEN: "TOGGLE_PREISDROPDOWN_HIDDEN",
  TOGGLE_ZIMMERDROPDOWN_HIDDEN: "TOGGLE_ZIMMERDROPDOWN_HIDDEN",
  TOGGLE_FLÄCHEDROPDOWN_HIDDEN: "TOGGLE_FLÄCHEDROPDOWN_HIDDEN",
  TOGGLE_BEZUGSARTDROPDOWN_HIDDEN: "TOGGLE_BEZUGSARTDROPDOWN_HIDDEN",
  TOGGLE_IMMOBILIENTYPDROPDOWN_HIDDEN: "TOGGLE_IMMOBILIENTYPDROPDOWN_HIDDEN",
  TOGGLE_RESULTS_HIDDEN: "TOGGLE_RESULTS_HIDDEN",
  TOGGLE_PAGECHANGERDROPDOWN_HIDDEN: " TOGGLE_PAGECHANGERDROPDOWN_HIDDEN",
  TOGGLE_ALL_DROPDOWNS_FALSE: "TOGGLE_ALL_DROPDOWNS_FALSE"
};

export default DropdownActionTypes;
