const DropdownActionTypes = {
  TOGGLE_PREISDROPDOWN_HIDDEN: "TOGGLE_PREISDROPDOWN_HIDDEN",
  TOGGLE_ZIMMERDROPDOWN_HIDDEN: "TOGGLE_ZIMMERDROPDOWN_HIDDEN",
  TOGGLE_FlÄCHEDROPDOWN_HIDDEN: "TOGGLE_lÄCHEDROPDOWN_HIDDEN",
  TOGGLE_BEZUGSARTDROPDOWN_HIDDEN: "TOGGLE_BEZUGSARTDROPDOWN_HIDDEN",
  TOGGLE_IMMOBILIENTYPDROPDOWN_HIDDEN: "TOGGLE_IMMOBILIENTYPDROPDOWN_HIDDEN",
  TOGGLE_ALL_DROPDOWNS_FALSE: "TOGGLE_ALL_DROPDOWNS_FALSE"
};

export default DropdownActionTypes;
