const DropdownActionTypes = {
  TOGGLE_PRICE_DROPDOWN_HIDDEN: "TOGGLE_PRICE_DROPDOWN_HIDDEN",
  TOGGLE_ROOMS_DROPDOWN_HIDDEN: "TOGGLE_ROOMS_DROPDOWN_HIDDEN",
  TOGGLE_SPACE_DROPDOWN_HIDDEN: "TOGGLE_SPACE_DROPDOWN_HIDDEN",
  TOGGLE_OBTAININGTYPE_DROPDOWN_HIDDEN: "TOGGLE_OBTAININGTYPE_DROPDOWN_HIDDEN",
  TOGGLE_REALESTATETYPE_DROPDOWN_HIDDEN:
    "TOGGLE_REALESTATETYPE_DROPDOWN_HIDDEN",
  TOGGLE_RESULTS_DROPDOWN_HIDDEN: "TOGGLE_RESULTS_DROPDOWN_HIDDEN",
  TOGGLE_PAGECHANGER_DROPDOWN_HIDDEN: " TOGGLE_PAGECHANGER_DROPDOWN_HIDDEN",
  TOGGLE_ALL_DROPDOWNS_FALSE: "TOGGLE_ALL_DROPDOWNS_FALSE"
};

export default DropdownActionTypes;
