const SliderActionType = {
  TOGGLE_LEFT: "TOGGLE_LEFT",
  TOGGLE_RIGHT: "TOGGLE_RIGHT",
  SET_SLIDER_POSITION: "SET_SLIDER_POSITION",
  RESET_SLIDER_POSITIONS: "RESET_SLIDER_POSITIONS"
};

export default SliderActionType;
